language: python
python:
- '2.7'
- '3.6'
- '3.7'
- '3.8'
install:
- pip install pipenv
- pipenv install 
- pip install .
script:
- pytest
deploy:
  distributions: sdist bdist_wheel
  skip_existing: true
  provider: pypi
  username: "__token__"
  password:
    secure: HxOVWv/5cR4J4XDNAg0iU80rnHsLtGToSY7MuxMLW5goWP89wSvpmUToYIDvns1cSgXnRgRRo2AyU2fYAhyFB03j0Ae5z46Ukf8/5a1SgVmfmYJFVIhlzEtZjiFleH6zMH83P/3/gt/jI1uzL0GgPaPySid8NfwQ5VukIUSY6UIujwr5gPvWu5qtnokWNxhEA4a52a2nUcK0gTaSj5B0xirDZo6ll19NxOYvI/XsL7u5vs9LIFq/2jC79IfXbKmh67ieu6PgSCtLiMNvNZbfRuxqFBX52fYZLF/gSrZGxnKkyFpScIhyEfsDW6C4I9+BVqgQE3Yi1OtreEkjiwqzsnWEDeyM4n7kloasVQKtkfQQrvrwBsepPTw+V6EsfE9+UFw8ixjc2NO6PAYcFZBWxOlvYTJesjRGG/37hp8IF99a3Ei4Styw/EUaHKfkb+WuLmMQdtQIAGAnLnNfnPGofKRVY4tkb6//257V20uO3BMA02tHXxizIUat1Gbx5/1/2p03AAQ18PiGc6Q3Fbbsnqo4cQKvDF4CkG68ONvy9foMWNtojjO+MW02Hwvq4QgNYXRoQ7fDFTH/krQaM3MRNcfjFp3sWZQz0U3OWIA+cJXYhURwdK2zebY5l0Q7eKSItUoUhpJSpX6kWYVoAICRHQ4WZcbWY1YXPDcF3MCL4b0=
