language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- pip install -r requirements.txt
- pip install .
script:
- pytest
# deploy:
#   provider: testpypi
#   username: "__token__"
#   password:
#     secure: IMv9JAu1t3ViO6QM3cCYnEAdNeU0zZJuei3IEKYI7HpBVXSEJePJrrXirGapqRgR5Py1VutKGMF6Qc5Ez2Gtmdpw9Zf+qJy9xDMeRNOxbb+ihq7eLvERhJteLzBnPjEjXQMdxN0bgwJ4EZOZYZR9Qa6AxWmwgdE19IMIH8x/8k+gnpsBgF6J/JghLjjCPgrvAVgBPyY3cdgIgzdg4zxxQolcxzvlnCMW7oV1QrYz3WY1c+CCSeAtnyxq8R/0JW7QnwUKhzpbl2vIgpfpP45MVjDbhKTS6hXU/N1iIWZ8dF8Cur41ztW2XaCcEt2Mm+DALAjXqMl+XX+oxE+eVcK6sGt25lh+ODZozITSVLA1W8k1WcncgX7KSouF3K70pk/LpvyTUdhU4GIaCGTarbxYNdFGiHkFdIyYOWWS+2gIwqeEC23mvaZycAA6U7Pu9Umigt7r7xwTyPE6BPeL78mqe18Ganc9IWY5lKyy5rtA5lX6hlYp7FDZTnr1m6fe6RqG9CNiQDCaOJeBuv9HJA7Zvpg+k3K86IYs/7GIKfrj/T2Kk3xjXds20pTcTwNKKayGwH7f4yAPi2tJV2VOa/dO0ap/QZrr4SNORfC1dMTO3NABZiWzQ8Q5xcT5rdBq7ChNiBy6v9wEVMJ/lBOAHhgEWtytYNpuQISWiwwVKM3t31s=
