language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- pip install -r requirements.txt
- pip install .
script:
- pytest
# deploy:
#   provider: pypi
#   username: __token__
#   password:
#     secure: ouDjkV0VckK8QtoFyvyGyTlWwv4aVkaZ0fBpQQ6FPj4gKyvkpCo06y+nHuddHKIcvWH8l81IpZIrKKpvcIl71fC/u7Oa7kLvYEKH0KVmdLUIuCBqsMpXtuoi6J8TXgyMYEF/eP1uOT4n+kyIbCZfJoGDeDags5MW+Ev4FIgtwQGrnnf74jEpOsRYW9jXUEQKlUch+6P9QukZOOKp0ba3gCRzElHqOCalMinD2ec0eSwsqPDdkkOYzjrbxLHDUyTmfLRH64YEx+JNQ0tl2tqHuHnrpN1jZ2XYMY8sIWPwSNaluOk/hibnFLUvYyB2Oc2stlBOzm3CSp18835mZKcyC/2T5lIAr+8gSh+IrGK28fqBO9n8IpltoDNzjXwBhU2o/YLGyac3W6+I8GMsQF6s4uWwrBCx5ewcNwwTQFk79gsLGGzBOsHuCbe1Q+YWw++DrE8Ay8PzvdKP2CbNc9Y2EmlO4aY0aZrS0aCBU134zRybDotQtL1E5O8n952N6XYCfIEuMvV6zznh6eBJbeJ+LvxMrOOLsXxdRSYiDlJigW9iOlhagH4V3uzcSINZdyl8Mf3uV4brJj/kUAyOdGB7paxLM3EjMTbK7cQIUZgIG0DaCQk7HfuHfH5WcwK5v1IC5uOmEzKStnGl34h1ySbzyyuQW1WVr1LRVdJNliRsz84=
