language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- pip install -r requirements.txt
- pip install .
script:
- pytest
deploy:
  provider: pypi
  username: __token__
  password:
    secure: jC8P3D6RJuIR+m+XT0krPpli+dXJ2XVeikMJPvb0377O2+PNiDAmpJnAMv3BnRmZDL9xc7P9Ack0mCUwQOpae+WQxd+bbS2l+GM+iAQ4aejnSC7Pa+dXi7auSklHFrknA6gDRUCzuV78h0HeIpxNSk+JnXiGGZmRjftYYf/9eZP/sShPc4Y51JrvKFJJEsENHFNhlvR6DeBUtP7tC/P4OKxY1LcKzCWY0ljmunXen5Z+OCcOtXmenDUuYf8gtfCeaFq7EFkr53T3yztqyiFpQUCSLCuv7ilu8X7i9DiCYFEbQsYR70GwGCAyjbjcHNH5BPlmBbxjqyYUaOR2LYfsDD2xFJDWIu/MzuQ8fb9JXlm/d3D5wJSyyicY4tSwqwOYnDdq5VJpoSZ1e141J3ztGRzKdRL28xROc3OXnWjgg/3bHF/XLgqpzvVZvrOzhOdfDoEzvNzku/1MqwCF0bv7t+xdGWCHOvTby5dNNBrvojqf95Nmz/adQIru5W9BwhGElY8glpFTi18FFAhnDyySeqIxSXfjeqsCtePo+1PyCd+90fhizoYqILAV4VxsVwD37flSb9Xj16UY9VaJMU7jRYM1FmbWHJvBl4y+IhSA2IdfIr94w4N81S6uOuXjmdPjOyN/LTnNK7MoKMKEh7BANcNwhkg59/HZQ8uPacPk774=
